### ISSUE TITLE
Re: change matrix represenation

### ISSUE THREAD

**Issue by gilbox** [honzabrecka/gama#5]
[This commit](https://github.com/honzabrecka/gama/commit/4659228869a05663ae01d468ef5baa4c3e8b5749) has some bug I haven't figured out yet, but l am also wondering about the `gama.Matrix` function signature. Should it be changed to this?

    gama.Matrix = function(a, b, tx, c, d, ty)

Currently it is this:

    gama.Matrix = function(a, b, c, d, tx, ty)

**Comment by gilbox** [comment]
I believe [this fixes](https://github.com/gilbox/gama/commit/bdd4ed626c45db5ba636a51b688af4000251a25b) the bug I mentioned, but still need to update UTs.

**Comment by honzabrecka** [comment]
I changed the signature as you proposed.

I don't think it is a bug - matrices is multiplied in `b * a` order, which may be confusing. I changed it to `a * b` to make it clear. Does the `subtract` function behave as you expected? Should it be changed to `a - b` too? What do you think?

**Comment by gilbox** [comment]
Interesting, I hadn't even thought of that. `a * b` and `a - b` seem more intuitive. However, I am not using those functions directly. I have a small app which does a series of transformations with gama. Some of those transformations (`translateMatrix`, `scaleMatrix`) use `multiplyMatrix` internally. When I upgraded to [this commit](https://github.com/honzabrecka/gama/commit/4659228869a05663ae01d468ef5baa4c3e8b5749) my app broke. However, when I made [this change](https://github.com/gilbox/gama/commit/bdd4ed626c45db5ba636a51b688af4000251a25b) it fixed it.

**Comment by honzabrecka** [comment]
Try your app with current master and let me know.

**Comment by gilbox** [comment]
Sure, I don't mind updating my app at all. However, my expectation was that certain operations would not require any change. For example, consider the following file (index.js):

```
const gama = require('gama');
const {Point} = gama;
const R = require('ramda');

const m = gama.EmptyMatrix();
const point = Point(2,3);

const xf1 = gama.translateMatrix(Point(5,10));
const xf2 = gama.scaleMatrix(Point(3,3));
const xf3 = gama.translateMatrix(Point(3,9));

demo(xf1);
demo(xf2, xf1);
demo(xf3, xf2, xf1);

function demo(...xf) {
  const matrix = R.compose(...xf)(m);
  const p = gama.transformPoint(matrix, point);
  console.log(p);
}
```

Now I execute the file like this, (this is copy+pasted from my terminal):

```
gbirman@gama-demo$ npm install gama
gama@1.0.0 node_modules/gama
└── ramda@0.13.0
gbirman@gama-demo$ babel-node ./
{ x: 7, y: 13 }
{ x: 11, y: 19 }
{ x: 20, y: 46 }
gbirman@gama-demo$ npm install https://github.com/honzabrecka/gama.git
gama@1.0.0 node_modules/gama
└── ramda@0.13.0
gbirman@gama-demo$ babel-node ./
{ x: 7, y: 13 }
{ x: 21, y: 39 }
{ x: 24, y: 48 }
```

Is that what you expected?

**Comment by honzabrecka** [comment]
You were right, there was a bug which is actually fixed: 2 + 5 = 7; 7 * 3 = 21; 21 + 3 = 24

Fixed version will be released soon.
